### ISSUE TITLE
Using Master Releases may be an issue

### ISSUE THREAD

**Issue by VinylVault** [MartinBarker/vinyl2digital#5]
Hi Martin, 

It may be better to use the `ReleaseId` rather than the `MasterId` when getting the details for releases, as some editions have different tracks than the master

**Comment by MartinBarker** [comment]
Updated vinyl2digital to include better Discogs error handling which should fix any errors when using the `-i discogs` option.
If you run this command it should update to version 1.0.3 and fix your problem(hopefully)
```
pip install --upgrade vinyl2digital
```

The `-i discogs` option will accept both release and master urls.

I tested with both master and release discog urls:

```
python3 -m vinyl2digital -i discogs https://www.discogs.com/release/6922993-Neville-Simmons-Sings-Caribbean-Holiday-Favorites -f flac -o "E:\martinradio\rips\vinyl\testrip"
```

```
python3 -m vinyl2digital -i discogs https://www.discogs.com/master/1227141-Alessandro-Alessandroni-Ritmo-DellIndustria-N2 -f flac -o "E:\martinradio\rips\vinyl\testrip"
```
