### ISSUE TITLE
Failure to run, tofile = open(toname, "w')

### ISSUE THREAD

**Issue by GlacierNester** [MartinBarker/vinyl2digital#9]
In attempting to run the program after opening audacity from both a powershell window and a standard command line, in the first attempt to run the code, regardless of whether that's using the -t flag, or just outright running an output, I'll get an error that looks like the following: 
![image](https://github.com/MartinBarker/vinyl2digital/assets/40207147/26c296ae-2912-46a0-a739-f77a0b75ba9d)
(roughly transcribed, it detects the mod-script-pipe, then throws an error in vinyl2digital's __init__.py, line 31, TOFILE = open(TONAME, 'w')
In then trying to run it a second time (whether re-running the -t flag, or attempting an output after the -t flag confirms the pipe exists and then throws that error), we get this error: 
![image](https://github.com/MartinBarker/vinyl2digital/assets/40207147/1b110fba-7df7-46f3-9e42-0883b109aaf4)
(transcribed, it says ..does not exist. Ensure Audacity is running with mod-script-pipe.) 
For clarity, here's the output of two runs with the -t flag enabled: 
![image](https://github.com/MartinBarker/vinyl2digital/assets/40207147/9214de13-fb5c-4c52-a2d9-6e4407b63825)
This effect is visible both from the documentation's suggested standard command line, and from a powershell window, and remains after attempting to ensure the code is updated using pip install --upgrade vinyl2digital. My best guess as to why the runs following the first throw the audacity not connected issue is that the exception being thrown by the first run disconnects the command line from Audacity. Looking at the file mentioned in the error, the error correctly suggests that the code seems to not be able to find the path assigned to TONAME, ('\\\\.\\pipe\\ToSrvPipe') but I'm not sure how to fix that, hence the issue report!

**Comment by MartinBarker** [comment]
just updated and was able to replicate error in Audacity 3.4.2, what version of audacity did you have error with?

**Comment by MartinBarker** [comment]
Released version v1.0.6, please update with `pip install --upgrade vinyl2digital`.
This release should fix the issue, I tested on win10 command prompt and audacity v 3.4.2 and was able to use the script to export selections. Let me know if you face anymore issues and I will re-open this issue. thx

**Comment by GlacierNester** [comment]
Runs as intended with Audacity 2.4.2! Much appreciated!
